# -*- coding: utf-8 -*-
"""Drift Detection in Answers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13npap-zkuwffWWGXXS6xfrQp4Pdowt92

Installation of Libraries
"""

!pip install transformers datasets scikit-learn scipy river

"""Import Libraries"""

import numpy as np
import pandas as pd

from transformers import BertTokenizer, BertModel
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

from scipy.spatial.distance import jensenshannon

"""**Customized Dataset**

This dataset consists of manually created B.Tech domain answers from subjects like Operating Systems, DBMS, Computer Networks, Machine Learning, Artificial Intelligence, and Software Engineering.

Each answer is assigned a score to simulate human grading. The dataset is designed to represent different writing styles and semantic variations, which are essential for testing drift detection.

**Limitation: Since this is a small synthetic dataset, it does not fully capture real-world student answer diversity. In future work, a larger real-world dataset such as the ASAP Automated Essay Scoring dataset will be used to improve robustness and realism of the model.**
"""

data = {
    "answer": [

        # Operating Systems
        "A process is a program in execution with its own memory space.",
        "Process is an active instance of a program allocated with system resources.",
        "Deadlock occurs when processes wait indefinitely for each other to release resources.",
        "Deadlock is a condition where circular waiting prevents processes from execution.",

        # DBMS
        "Normalization reduces redundancy and improves data integrity in databases.",
        "Database normalization organizes tables to eliminate redundancy and anomalies.",
        "A primary key uniquely identifies each record in a table.",
        "Primary key is a unique identifier for tuples in a relation.",

        # Computer Networks
        "TCP is a connection oriented protocol that ensures reliable communication.",
        "TCP provides reliable and ordered delivery of packets.",
        "IP protocol handles addressing and routing of packets across networks.",
        "IP is responsible for logical addressing and packet routing.",

        # Machine Learning
        "Overfitting occurs when a model learns noise instead of actual patterns.",
        "Overfitting leads to poor generalization on unseen data.",
        "Supervised learning uses labeled data to train machine learning models.",
        "In supervised learning, models learn from input output pairs.",

        # Artificial Intelligence
        "Artificial Intelligence enables machines to simulate human intelligence.",
        "AI allows machines to perform tasks that require human intelligence.",

        # Cloud Computing
        "Cloud computing provides on demand access to computing resources.",
        "Cloud computing enables scalable and remote access to services.",

        # Software Engineering
        "Agile methodology focuses on iterative development and customer collaboration.",
        "Agile promotes continuous feedback and incremental improvements.",
        "Software testing ensures that the system meets requirements and is error free.",
        "Testing verifies and validates the functionality of software systems."
    ],

    "score": [
        5, 5, 4, 4,
        5, 5, 4, 4,
        5, 5, 4, 4,
        3, 3, 5, 5,
        4, 4,
        5, 5,
        4, 4,
        5, 5
    ]
}

df = pd.DataFrame(data)
df.head()

"""Train Test Split"""

train_df = df.sample(frac=0.7, random_state=42)
test_df = df.drop(train_df.index)

train_texts = train_df['answer']
train_labels = train_df['score']

test_texts = test_df['answer']
test_labels = test_df['score']

"""**Load BERT**

This cell loads the **pre-trained BERT model and tokenizer.** BERT is used to generate contextual embeddings that capture semantic meaning of student answers.
"""

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = BertModel.from_pretrained('bert-base-uncased')

"""**Convert Text to Embeddings**

This function converts textual answers into numerical embeddings using BERT. The CLS token embedding is used as a representation of the entire sentence.
"""

def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

    with torch.no_grad():
        outputs = bert_model(**inputs)

    embedding = outputs.last_hidden_state[:, 0, :].numpy()
    return embedding

"""**Generate Embeddings**

This step converts all training and testing answers into high-dimensional semantic embeddings using the BERT model.
"""

train_embeddings = np.vstack([get_embedding(text) for text in train_texts])
test_embeddings = np.vstack([get_embedding(text) for text in test_texts])

"""Model Training

**Why Random Forest after BERT?**

BERT is used for semantic feature extraction, and Random Forest is used as a regression model for grading based on those embeddings.

"""

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor()
rf_model.fit(train_embeddings, train_labels)

test_preds = rf_model.predict(test_embeddings)

"""Baseline Evaluation using **accuracy and F1 score.**"""

from sklearn.metrics import accuracy_score, f1_score, mean_absolute_error, mean_squared_error

# Predictions
raw_test_preds = rf_model.predict(test_embeddings)
rounded_test_preds = np.round(raw_test_preds)

print("\n--- Baseline Evaluation ---")
print("Accuracy:", accuracy_score(test_labels, rounded_test_preds))
print("F1 Score:", f1_score(test_labels, rounded_test_preds, average='weighted'))
print("MAE:", mean_absolute_error(test_labels, raw_test_preds))
print("MSE:", mean_squared_error(test_labels, raw_test_preds))

"""**Drift Simulation**

This cell simulates new incoming student answers. These responses represent changes in writing style and expression, which may introduce concept drift in the model.
"""

new_answers = [
    "Processes execute programs and manage memory dynamically.",
    "Deadlock happens due to circular wait between processes.",
    "Normalization removes redundancy from database tables.",
    "TCP ensures reliable communication between devices.",
    "Overfitting reduces model generalization capability."
]

new_scores = [5, 4, 5, 4, 3]

new_df = pd.DataFrame({
    "answer": new_answers,
    "score": new_scores
})

new_embeddings = np.vstack([get_embedding(text) for text in new_df['answer']])

"""Performance on New Data"""

# Predictions on new data
raw_new_preds = rf_model.predict(new_embeddings)
rounded_new_preds = np.round(raw_new_preds)

print("\n--- New Data Evaluation (Before Retraining) ---")
print("Accuracy:", accuracy_score(new_df['score'], rounded_new_preds))
print("F1 Score:", f1_score(new_df['score'], rounded_new_preds, average='weighted'))
print("MAE:", mean_absolute_error(new_df['score'], raw_new_preds))
print("MSE:", mean_squared_error(new_df['score'], raw_new_preds))

"""Compute Drift using **Jensen-Shannon divergence**"""

def compute_drift(old, new):
    old_mean = np.mean(old, axis=0)
    new_mean = np.mean(new, axis=0)

    old_prob = np.abs(old_mean)
    new_prob = np.abs(new_mean)

    old_prob = old_prob / np.sum(old_prob)
    new_prob = new_prob / np.sum(new_prob)

    drift = jensenshannon(old_prob, new_prob)
    return drift

drift_score = compute_drift(train_embeddings, new_embeddings)

print("Drift Score:", drift_score)

"""**Trigger Retraining**

If the drift score exceeds a threshold, the model is retrained using both old and new data. This allows the model to adapt to changing patterns in student answers.
"""

if drift_score > 0.1:
    print("Drift detected → Retraining model")

    combined_embeddings = np.vstack((train_embeddings, new_embeddings))
    combined_labels = np.concatenate((train_labels, new_df['score']))

    rf_model.fit(combined_embeddings, combined_labels)

"""Final Evaluation after Retraining"""

# Predictions after retraining
raw_updated_preds = rf_model.predict(new_embeddings)
rounded_updated_preds = np.round(raw_updated_preds)

print("\n--- After Retraining Evaluation ---")
print("Accuracy:", accuracy_score(new_df['score'], rounded_updated_preds))
print("F1 Score:", f1_score(new_df['score'], rounded_updated_preds, average='weighted'))
print("MAE:", mean_absolute_error(new_df['score'], raw_updated_preds))
print("MSE:", mean_squared_error(new_df['score'], raw_updated_preds))

"""**Accuracy became 1.0 — is that realistic?**

Since the dataset is small and controlled, the model achieves perfect accuracy after retraining. In real-world large datasets, improvement would be significant but not necessarily perfect.

**Graph using Matplotlib**

The graph shows that after introducing new data, the model’s accuracy decreased, indicating the presence of concept drift. Once drift was detected, the model was retrained using updated data, which restored and improved its performance. This validates the effectiveness of the drift detection and adaptive retraining pipeline.
"""

import matplotlib.pyplot as plt

before_mae = mean_absolute_error(new_df['score'], raw_new_preds)
after_mae = mean_absolute_error(new_df['score'], raw_updated_preds)

plt.bar(["Before Retraining", "After Retraining"], [before_mae, after_mae])
plt.title("MAE Improvement After Drift Handling")
plt.ylabel("MAE")
plt.show()

"""**Limitations:**

1. Dataset is synthetic
2. Perfect accuracy due to small dataset

**Mitigation**

The limitations of using a small synthetic dataset and achieving perfect accuracy are mitigated by positioning this work as a proof-of-concept, with future implementation planned on larger real-world datasets to ensure realistic performance evaluation and generalization.

**Note:** Use Fine Tuned BERT next, instead of BERT and Random Forest
"""